# Generated by Django 4.2.7 on 2026-03-10 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_merge_20251003_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_personal', models.CharField(choices=[('colaborador', 'Colaborador'), ('trabajador_diario', 'Trabajador Diario')], max_length=20, verbose_name='Tipo de Personal')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tardanza', 'Tardanza'), ('permiso', 'Permiso'), ('vacaciones', 'Vacaciones'), ('feriado', 'Feriado')], default='presente', max_length=20, verbose_name='Estado')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.colaborador', verbose_name='Colaborador')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='core.proyecto', verbose_name='Proyecto')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('trabajador_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.trabajadordiario', verbose_name='Trabajador Diario')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
