# Generated by Django 4.2.7 on 2026-03-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_asistencias_module'),
        ('core', '0028_merge_20251006_1542'),
    ]

    operations = [
    ]
