# Generated by Django 4.2.7 on 2026-04-24 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_registro_trabajo_dias_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocercaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('circle', 'Círculo'), ('polygon', 'Polígono')], max_length=10, verbose_name='Tipo')),
                ('configuracion', models.JSONField(verbose_name='Configuración')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geocerca', to='core.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Geocerca',
                'verbose_name_plural': 'Geocercas',
            },
        ),
    ]
