# Generated by Django 4.2.7 on 2026-04-24 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_geocerca_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_personal', models.CharField(choices=[('colaborador', 'Colaborador'), ('trabajador_diario', 'Trabajador Diario')], max_length=20, verbose_name='Tipo de Personal')),
                ('tipo', models.CharField(choices=[('goce', 'Permiso con goce de sueldo'), ('sin_goce', 'Permiso sin goce de sueldo'), ('incapacidad', 'Incapacidad médica'), ('duelo', 'Duelo familiar'), ('paternidad', 'Paternidad / Maternidad'), ('vacaciones', 'Vacaciones'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Permiso')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('dias_totales', models.PositiveIntegerField(default=1, verbose_name='Días Solicitados')),
                ('motivo', models.TextField(verbose_name='Motivo / Justificación')),
                ('documento_adjunto', models.CharField(blank=True, max_length=500, verbose_name='Referencia de Documento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('observaciones_resolucion', models.TextField(blank=True, verbose_name='Observaciones de Resolución')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado / Rechazado por')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_ausencia', to='core.colaborador', verbose_name='Colaborador')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_ausencia', to='core.proyecto', verbose_name='Proyecto')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('trabajador_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_ausencia', to='core.trabajadordiario', verbose_name='Trabajador Diario')),
            ],
            options={
                'verbose_name': 'Permiso / Ausencia',
                'verbose_name_plural': 'Permisos y Ausencias',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
